# -*- coding: utf-8 -*-
"""Untitled237.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fq9f-cN1jNC8PCDredzxFWC1yOb98v2m
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import fashion_mnist

(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

X_train.shape

X_train[0]

X_train[100]

X_train[59000]

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten,Activation

model=Sequential()

model.add(Flatten(input_shape=[28,28]))
model.add(Dense(200,activation="relu")) #anything

model.add(Dense(10,activation='softmax'))

model.compile(optimizer='adam',loss="sparse_categorical_crossentropy",metrics=["accuracy"])

model.fit(X_train,y_train,epochs=20)

### Challenge: Accuracy -> 90%